#
# KoolSMPCore v2.0 Configuration File
#

server:
  motd: KoolFreedom SMP (Native 1.21.1)

# Toggles the announcer
enable-announcer: true

# Time between each announcement
announcer-time: 2400

# Announcements
messages:
  discord:
    - "&c[&6KoolFreedom&c] Remember to join our Discord with &6'/discord'&c."
  report:
    - "&c[&6KoolFreedom&c] Got a rule breaker on the server? use &6'/report' &cto submit a report."
  owner:
    - "&c[&6KoolFreedom&c] &6gamingto12&c is the Owner of KoolFreedom."

# This is for the ReportCommand only
discord:
  report_channel_id: "REPORT_CHANNEL_ID"