# Toggles the announcer
enable-announcer: true

# Time between each announcement
announcer-time: 2400

# Announcements
messages:
  discord:
    - "&c[&6KoolFreedom&c] Remember to join our Discord with &6'/discord'&c."
  report:
    - "&c[&6KoolFreedom&c] Got a rule breaker on the server? use &6'/report' &cto submit a report."
  suggestion:
    - "&c[&6KoolFreedom&c] Have a suggestion? Join our Discord and put it there, the staff will review it."