#
# KoolSMPCore v3.0 Configuration File
#

server:
  motd: '<randomize>KoolFreedom SMP (Native 1.21.1)'
  tablist_header: ' <newline>  <light_purple>Welcome to <gold>KoolFreedom SMP</gold>!  <newline> '
  tablist_footer: ' <newline>  <light_purple>Join our <dark_purple>/discord</dark_purple> <newline>  '
  website_or_forum: 'Put your own forum/website here.'

# Toggles the announcer
enable-announcer: true

# Time between each announcement
announcer-time: 2400

# Announcements
messages:
  discord:
    - "&c[&6KoolFreedom&c] Remember to join our Discord with &6'/discord'&c."
  report:
    - "&c[&6KoolFreedom&c] Got a rule breaker on the server? use &6'/report' &cto submit a report."
  owner:
    - "&c[&6KoolFreedom&c] &6gamingto12&c is the Owner of KoolFreedom."

# Words that if detected in a chat message, results in the user being banned for hate speech
chat-filter:
  hate-speech:
    - nigger
    - n1gger
    - nigga
    - n1gga
    - niga
    - faggot
    - fagg0t
    - fag
    - heil hitler
    - seig heil
    - tranny

# Admin Chat Format
formats:
  admin_chat: "<dark_gray>[<aqua>AC</aqua>] <blue><name></blue> [<rank>] <gold><message>"
  commandspy: "<gray><hover:show_text:'<translate:chat.copy.click>'><click:copy_to_clipboard:<name>><name></click></hover>: <click:suggest_command:'<raw_command>'><command>"
  report: "<dark_gray>[<red>REPORTS</red>] <gold><reporter></gold> <red>has reported <gold><player></gold> for <gold><reason></gold>."
  say: "<light_purple>[Server:<name>] <message>"

discord:
  bot_token: ""
  report_channel_id: ""

unbannable_usernames:
  - gamingto12
