#
# KoolSMPCore v3.0 Configuration File
#

server:
  motd: '<randomize>KoolFreedom SMP (Native 1.21.1)'
  tablist_header: ' <newline>  <light_purple>Welcome to <gold>KoolFreedom SMP</gold>!  <newline> '
  tablist_footer: ' <newline>  <light_purple>Join our <dark_purple>/discord</dark_purple> <newline>  '
  website_or_forum: 'Put your own forum/website here.'

# All things related to the announcer
announcer:
  # Toggles the announcer
  enable: true

  # Time in ticks between each announcement
  delay: 2400

  # Announcer's messages, formatted in MiniMessage
  messages:
    - "<red>[<gold>KoolFreedom</gold>] Remember to join our Discord with <gold><click:suggest_command:/discord>'/discord'</click></gold>."
    - "<red>[<gold>KoolFreedom</gold>] Dealing with a rule-breaker? Use <gold><click:suggest_command:/report>'/report'</click></gold> to submit a report."
    - "<red>[<gold>KoolFreedom</gold>] <gold>gamingto12</gold> is the owner of KoolFreedom."

# Words that if detected in a chat message, results in the user being banned for hate speech
chat-filter:
  hate-speech:
    - nigger
    - n1gger
    - nigga
    - n1gga
    - niga
    - faggot
    - fagg0t
    - fag
    - heil hitler
    - seig heil
    - tranny

# Admin Chat Format
formats:
  admin_chat: "<dark_gray>[<aqua>AC</aqua>] <blue><name></blue> [<rank>] <gold><message>"
  commandspy: "<gray><hover:show_text:'<translate:chat.copy.click>'><click:copy_to_clipboard:<name>><name></click></hover>: <click:suggest_command:'<raw_command>'><command>"
  report: "<dark_gray>[<red>REPORTS</red>] <gold><reporter></gold> <red>has reported <gold><player></gold> for <gold><reason></gold>."
  say: "<light_purple>[Server:<name>] <message>"

discord:
  bot_token: ""
  server_id: ""
  report_channel_id: ""

# Groups that show up in places like admin chat
groups:
  default:
    name: default
    color: gray
    displayName: <gray>Member
  mod:
    name: mod
    color: green
    displayName: <green>Moderator
  admin:
    name: admin
    color: aqua
    displayName: <aqua>Admin
  senior:
    name: senior
    color: gold
    displayName: <gold>Senior
  developer:
    name: developer
    color: dark_purple
    displayName: <dark_purple>Developer
  manager:
    name: manager
    color: light_purple
    displayName: <light_purple>Manager
  co_owner:
    name: co_owner
    color: red
    displayName: <red>Co-Owner
  executive:
    name: executive
    color: dark_red
    displayName: <dark_red>Executive
  owner:
    name: owner
    color: red
    displayName: <red>Owner

unbannable_usernames:
  - gamingto12
