#
# KoolSMPCore v3.0 Configuration File
#

server:
  motd: KoolFreedom SMP (Native 1.21.1)
  tablist_header: ' \n  &dWelcome to &6KoolFreedom SMP&d!  \n '
  tablist_footer: ' \n  &dJoin our &5/discord \n  '
  website_or_forum: 'Put your own forum/website here.'

# Toggles the announcer
enable-announcer: true

# Time between each announcement
announcer-time: 2400

# Announcements
messages:
  discord:
    - "&c[&6KoolFreedom&c] Remember to join our Discord with &6'/discord'&c."
  report:
    - "&c[&6KoolFreedom&c] Got a rule breaker on the server? use &6'/report' &cto submit a report."
  owner:
    - "&c[&6KoolFreedom&c] &6gamingto12&c is the Owner of KoolFreedom."

discord:
  bot_token: ""
  report_channel_id: ""
  staff_action_channel_id: ""
