name: KoolSMPCore
main: eu.koolfreedom.KoolSMPCore
version: ${buildVersion}
description: Core plugin for the KoolFreedom SMP
load: POSTWORLD
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    LuckPerms:
      load: BEFORE
      required: false
    packetevents:
      load: BEFORE
      required: false
      join-classpath: true
    Essentials:
      load: BEFORE
      required: false
    EssentialsDiscord:
      load: BEFORE
      required: false
      join-classpath: true
    EssentialsDiscordLink:
      load: BEFORE
      required: false
      join-classpath: true
    DiscordSRV:
      load: BEFORE
      required: false
authors:
  - "gamingto12"
  - "_1kz"
  - "videogamesm12"
  - "sapph-ic"
api-version: "26.2"

permissions:
  kfc.member:
    description: Permissions for regular players
    default: not op
    children:
      - kfc.admininfo
      - kfc.koolsmpcore
      - kfc.playtime
      - kfc.reaction
      - kfc.report
      - kfc.seen
  kfc.admin:
    description: Permission group offering basic administrative tools, but leaving the more important stuff locked away
    default: op
    children:
      - kfc.member
      - kfc.adminchat
      - kfc.alts
      - kfc.ban
      - kfc.banip
      - kfc.banlist
      - kfc.blockcommand
      - kfc.clearchat
      - kfc.commandspy
      - kfc.freeze
      - kfc.heal
      - kfc.kick
      - kfc.lockup
      - kfc.mute
      - kfc.mutechat
      - kfc.notes.add
      - kfc.notes.view
      - kfc.notes.remove
      - kfc.note
      - kfc.orbit
      - kfc.rawsay
      - kfc.reports
      - kfc.satisfyall
      - kfc.say
      - kfc.seen.viewip
      - kfc.smite
      - kfc.spectate
      - kfc.tban
      - kfc.troll
      - kfc.unban
      - kfc.unblockcmd
      - kfc.warn
      - kfc.ping_everyone
      - kfc.playtime.others
  kfc.senior:
    description: Permission group offering some additional administrative capabilities, plus the ability to doom people.
    default: op
    children:
      - kfc.admin
      - kfc.banlist.reload
      - kfc.cage
      - kfc.reload
      - kfc.doom
      - kfc.reports.reopen
      - kfc.reports.handle
      - kfc.reports.close
  kfc.exec:
    description: Permission group offering pretty much everything the plugin has to offer, plus some fun commands
    default: op
    children:
      - kfc.senior
      - kfc.antispam.bypass
      - kfc.crash
      - kfc.reports.purge
      - kfc.update
