name: KoolSMPCore
main: eu.koolfreedom.KoolSMPCore
version: ${project.version}
description: Core plugin for the KoolFreedom SMP
depend:
  - Vault
softdepend:
  - ProtocolLib
  - LuckPerms
  - EssentialsDiscord
  - EssentialsDiscordLink
  - DiscordSRV
authors:
  - "gamingto12"
  - "_sftp"
  - "videogamesm12"
api-version: 1.21.1
# plugin.yml is no longer used to define commands, rather define permission nodes for commands that don't already have one
#  defined in the command class.
permissions:
  kfc.member:
    description: Permissions for regular players
    default: not op
    children:
      - kfc.command.admininfo
      - kfc.command.cry
      - kfc.command.hug
      - kfc.command.kiss
      - kfc.command.koolsmpcore
      - kfc.command.pat
      - kfc.command.poke
      - kfc.command.report
      - kfc.command.seen
      - kfc.command.ship
      - kfc.command.slap
  kfc.admin:
    description: Permission group offering basic administrative tools, but leaving the more important stuff locked away
    default: op
    children:
      - kfc.member
      - kfc.command.adminchat
      - kfc.command.ban
      - kfc.command.banip
      - kfc.command.banlist
      - kfc.command.blockcommand
      - kfc.command.clearchat
      - kfc.command.clearchat.immune
      - kfc.command.commandspy
      - kfc.command.freeze
      - kfc.command.heal
      - kfc.command.kick
      - kfc.command.mute
      - kfc.command.mute.immune
      - kfc.command.mutechat
      - kfc.mutechat.bypass
      - kfc.notes.add
      - kfc.notes.view
      - kfc.command.note
      - kfc.command.orbit
      - kfc.command.rawsay
      - kfc.command.reports
      - kfc.command.satisfyall
      - kfc.command.say
      - kfc.seen.viewip
      - kfc.command.smite
      - kfc.command.spectate
      - kfc.command.troll
      - kfc.command.unban
      - kfc.command.unblockcmd
      - kfc.command.warn
      - kfc.command.warn.immune
      - kfc.ping_everyone
  kfc.senior:
    description: Permission group offering some additional administrative capabilities, plus the ability to doom people.
    default: op
    children:
      - kfc.admin
      - kfc.antispam.bypass
      - kfc.command.banlist.reload
      - kfc.command.cage
      - kfc.command.koolsmpcore.reload
      - kfc.command.doom
  kfc.exec:
    description: Permission group offering pretty much everything the plugin has to offer, plus some fun commands
    default: op
    children:
      - kfc.senior
      - kfc.command.crash
      - kfc.command.reports.purge
libraries:
  - org.javassist:javassist:3.29.1-GA
