name: KoolSMPCore
main: eu.koolfreedom.KoolSMPCore
version: 1.0
api-version: 1.20
description: Core plugin for the KoolFreedom SMP
depend: [ ProtocolLib, WorldGuard ]
softdepend: [ Essentials ]
authors: [gamingto12]
commands:
  clearchat:
    permission: kf.admin
    aliases: [chatclear, cc]
    description: Clears the chat
  report:
    description: Reports a suspicious player
  koolsmpcore:
    description: Displays information about the plugin
  obliterate:
    description: Send someone straight to hell
    permission: kf.senior
  spectate:
    permission: kf.admin
    description: Allows you to spectate someone
  cmdspy:
    aliases: [cspy, commandspy]
    permission: kf.admin
    description: Enables/Disables CommandSpy

permissions:
  kf.admin:
    default: op
  kf.senior:
    default: op
  kf.cmdspy.exempt:
    default: op
  kf.cmdspy.others:
    default: op
