name: KoolSMPCore
main: eu.koolfreedom.KoolSMPCore
version: 2.2
api-version: 1.20
description: Core plugin for the KoolFreedom SMP
depend: [ ProtocolLib, WorldGuard, LuckPerms ]
softdepend: [ Essentials ]
authors: [gamingto12, 0x7694C9]
commands:
  adminchat:
    usage: /<command> <message>
    description: Speak with other staff members
    aliases: [ o, oc, adminchat, ac ]
  ban:
    description: Ban someone
    aliases: [gtfo]
  banip:
    description: Ban someone....but their IP
    aliases: [ipban]
  clearchat:
    aliases: [cc]
    permission: kf.admin
    description: Clears the chat
  commandspy:
    aliases: [cmdspy, cspy]
    description: Spy on another player's commands.
  crash:
    permission: kf.exec
    description: Crash a person's client
  cry:
    description: womp womp
  doom:
    description: Swing the Russian Hammer
  hug:
    descriptions: Hug a player
  kick:
    description: Kick someone
  kiss:
    description: For the lovebirds, give em a big ol kiss
  koolsmpcore:
    description: Display information about the plugin
    aliases: [kfm]
  lagsource:
    permission: kf.admin
    description: Displays information about potential lag sources
  mute:
    description: Mutes a player
  obliterate:
    description: Unleash hell upon a player
  pat:
    description: pat pat
  poke:
    description: poke
  rawsay:
    description: Tellraw...but better
    permission: kf.admin
  report:
    description: Report a suspicious user
  satisfyall:
    description: Feed and heal everyone online
    usage: /<command>
  say:
    permission: kf.admin
    description: what the fuck else does it do
  ship:
    description: Make a really unfunny joke about how you ship 2 people
  slap:
    description: Slap the shit out of someone
  smite:
    permission: kf.admin
    description: Smite that motherfucker
  spectate:
    description: Suspicious user? Spectate them
  unban:
    description: Unban someone
  unbanip:
    description: Unbans someone....but their IP!!!!
  unmute:
    description: Unmute someone
  warn:
    description: Warn someone
permissions:
  kf.admin:
    default: op
  kf.senior:
    default: op
