name: KoolSMPCore
main: eu.koolfreedom.KoolSMPCore
version: ${project.version}
description: Core plugin for the KoolFreedom SMP
depend:
  - Vault
softdepend:
  - ProtocolLib
  - LuckPerms
  - EssentialsDiscord
  - EssentialsDiscordLink
  - DiscordSRV
authors:
  - "gamingto12"
  - "0x7694C9"
  - "videogamesm12"
api-version: 1.21.1
permissions:
  kfc.member:
    description: Permissions for regular players
    default: not op
    children:
      - kfc.command.admininfo
      - kfc.command.cry
      - kfc.command.hug
      - kfc.command.kiss
      - kfc.command.koolsmpcore
      - kfc.command.pat
      - kfc.command.poke
      - kfc.command.report
      - kfc.command.ship
      - kfc.command.slap
  kfc.admin:
    description: Permission group offering basic administrative tools, but leaving the more important stuff locked away
    default: op
    children:
      - kfc.member
      - kfc.command.adminchat
      - kfc.command.ban
      - kfc.command.banip
      - kfc.command.clearchat
      - kfc.command.clearchat.immune
      - kfc.command.commandspy
      - kfc.command.entitywipe
      - kfc.command.kick
      - kfc.command.mute
      - kfc.command.mute.immune
      - kfc.command.orbit
      - kfc.command.rawsay
      - kfc.command.reports
      - kfc.command.satisfyall
      - kfc.command.say
      - kfc.command.smite
      - kfc.command.spectate
      - kfc.command.troll
      - kfc.command.unban
      - kfc.command.warn
      - kfc.command.warn.immune
      - kfc.ping_everyone
  kfc.senior:
    description: Permission group offering some additional administrative capabilities, plus the ability to doom people.
    default: op
    children:
      - kfc.admin
      - kfc.command.banlist.reload
      - kfc.command.koolsmpcore.reload
      - kfc.command.doom
      - kfc.command.unloadchunks
  kfc.exec:
    description: Permission group offering pretty much everything the plugin has to offer, plus some fun commands
    default: op
    children:
      - kfc.senior
      - kfc.command.crash
      - kfc.command.reports.purge