name: KoolSMPCore
main: eu.koolfreedom.KoolSMPCore
version: 1.2
api-version: 1.20
description: Core plugin for the KoolFreedom SMP
depend: [ ProtocolLib, WorldGuard, LuckPerms ]
softdepend: [ Essentials ]
authors: [gamingto12]

permissions:
  kf.admin:
    default: op
  kf.senior:
    default: op
