name: KoolSMPCore
main: eu.koolfreedom.KoolSMPCore
version: 2.0
api-version: 1.20
description: Core plugin for the KoolFreedom SMP
depend: [ ProtocolLib, WorldGuard, LuckPerms ]
softdepend: [ Essentials ]
authors: [gamingto12, 0x7694C9]
commands:
  clearchat:
    aliases: [cc]
    permission: kf.admin
    description: Clears the chat
  crash:
    permission: kf.exec
    description: Crash a person's client
  doom:
    permission: kf.senior
    description: Swing the Russian Hammer
  hug:
    descriptions: Hug a player
  kiss:
    description: For the lovebirds, give em a big ol kiss
  koolsmpcore:
    description: Display information about the plugin
    aliases: [kfm]
  lagsource:
    permission: kf.admin
    description: Displays information about potential lag sources
  obliterate:
    permission: kf.senior
    description: Unleash hell upon a player
  pat:
    description: pat pat
  poke:
    description: poke
  rawsay:
    description: Tellraw...but better
    permission: kf.admin
  report:
    description: Report a suspicious user
  say:
    permission: kf.admin
    description: what the fuck else does it do
  ship:
    description: Make a really unfunny joke about how you ship 2 people
  slap:
    description: Slap the shit out of someone
  smite:
    permission: kf.admin
    description: Smite that motherfucker
  spectate:
    description: Suspicious user? Spectate them

permissions:
  kf.admin:
    default: op
  kf.senior:
    default: op
